version: "3.9"

services:
  django:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - postgresql
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
  postgresql:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker
      - POSTGRES_USER=docker
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
