# Generated by Django 3.2.4 on 2021-07-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on wich the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Date time on wich the object was las modified.', verbose_name='modified at')),
                ('provider', models.CharField(choices=[('prov_1', 'Diario oficial de la federación'), ('prov_2', 'Fixer'), ('prov_3', 'Banxico')], help_text='A list of authorized providers', max_length=48)),
                ('value', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
